// ─────────────────────────────────────────────────────────────────────────────
// app/lib/subjects.ts
// ─────────────────────────────────────────────────────────────────────────────

import { Subject, SubjectId, Discipline } from '../types'

export const DISCIPLINES: { id: Discipline; label: string; icon: string }[] = [
  { id: 'mbbs', label: 'MBBS', icon: '🩺' },
  { id: 'bds',  label: 'BDS',  icon: '🦷' },
]

export const SUBJECTS: Subject[] = [
  // ──────────────────────────────────────────────────────────────
  // MBBS Subjects
  // ──────────────────────────────────────────────────────────────
  {
    id:          'anatomy',
    label:       'Anatomy',
    icon:        '🦴',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Gross, neuro & clinical anatomy',
    year:        1,
    discipline:  'mbbs',
    topics: [
      'Brachial plexus',
      'Circle of Willis',
      'Femoral triangle',
      'Carpal tunnel',
      'Inguinal canal',
    ],
  },
  {
    id:          'physiology',
    label:       'Physiology',
    icon:        '❤️',
    color:       'physio',
    accent:      '#ffd60a',
    description: 'Cardiovascular, renal & neuro',
    year:        1,
    discipline:  'mbbs',
    topics: [
      'Action potential',
      'Frank-Starling law',
      'Renin-angiotensin',
      'Starling forces',
      'Cardiac cycle',
    ],
  },
  {
    id:          'biochemistry',
    label:       'Biochemistry',
    icon:        '⚗️',
    color:       'biochem',
    accent:      '#c77dff',
    description: 'Metabolism, enzymes & genetics',
    year:        1,
    discipline:  'mbbs',
    topics: [
      'Krebs cycle',
      'Glycolysis steps',
      'DNA replication',
      'Urea cycle',
      'Fatty acid synthesis',
    ],
  },
  {
    id:          'pharmacology',
    label:       'Pharmacology',
    icon:        '💊',
    color:       'pharma',
    accent:      '#4df7c8',
    description: 'Drug classes, MOA & toxicology',
    year:        2,
    discipline:  'mbbs',
    topics: [
      'Beta blockers',
      'ACE inhibitors',
      'Warfarin mechanism',
      'Penicillin MOA',
      'Opioid receptors',
    ],
  },
  {
    id:          'pathology',
    label:       'Pathology',
    icon:        '🔬',
    color:       'patho',
    accent:      '#fb923c',
    description: 'General & systemic pathology',
    year:        2,
    discipline:  'mbbs',
    topics: [
      'MI zones',
      'Virchow\'s triad',
      'Cell injury types',
      'Amyloidosis',
      'Neoplasia grades',
    ],
  },
  {
    id:          'microbiology',
    label:       'Microbiology',
    icon:        '🦠',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Bacteria, viruses & immunity',
    year:        2,
    discipline:  'mbbs',
    topics: [
      'Gram positive cocci',
      'TB pathogenesis',
      'HIV life cycle',
      'Complement system',
      'Hepatitis viruses',
    ],
  },
  {
    id:          'medicine',
    label:       'Medicine',
    icon:        '🩺',
    color:       'green',
    accent:      '#0df27d',
    description: 'Internal medicine & clinical',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Heart failure criteria',
      'Diabetes management',
      'ECG interpretation',
      'Thyroid disorders',
      'Acid-base balance',
    ],
  },
  {
    id:          'surgery',
    label:       'Surgery',
    icon:        '🔪',
    color:       'pharma',
    accent:      '#4df7c8',
    description: 'General, ortho & clinical surgery',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Hernia types',
      'Wound healing',
      'Bowel obstruction',
      'Appendicitis signs',
      'Thyroid surgery',
    ],
  },
  {
    id:          'obgyn',
    label:       'OBGYN',
    icon:        '🤰',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Obstetrics & gynaecology',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Menstrual cycle hormones',
      'Stages of labour',
      'Pre-eclampsia',
      'Placenta praevia',
      'Contraception methods',
    ],
  },
  {
    id:          'pediatrics',
    label:       'Pediatrics',
    icon:        '👶',
    color:       'physio',
    accent:      '#ffd60a',
    description: 'Child health & development',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Neonatal jaundice',
      'Immunisation schedule',
      'Kwashiorkor vs Marasmus',
      'Congenital heart defects',
      'Childhood pneumonia',
    ],
  },
  {
    id:          'psychiatry',
    label:       'Psychiatry',
    icon:        '🧠',
    color:       'biochem',
    accent:      '#c77dff',
    description: 'Mental health & disorders',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Schizophrenia symptoms',
      'Depression criteria',
      'Bipolar disorder types',
      'Anxiety disorders',
      'Antipsychotic drugs',
    ],
  },
  {
    id:          'dermatology',
    label:       'Dermatology',
    icon:        '🩹',
    color:       'patho',
    accent:      '#fb923c',
    description: 'Skin conditions & disorders',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Psoriasis types',
      'Eczema pathogenesis',
      'Skin cancer types',
      'Acne vulgaris',
      'Fungal skin infections',
    ],
  },
  {
    id:          'orthopedics',
    label:       'Orthopedics',
    icon:        '🦿',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Musculoskeletal & fractures',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Fracture classification',
      'Osteoarthritis vs RA',
      'Bone tumour types',
      'Nerve injuries',
      'Spinal cord lesions',
    ],
  },
  {
    id:          'ent',
    label:       'ENT',
    icon:        '👂',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Ear, nose & throat',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Otitis media types',
      'Tonsillitis complications',
      'Laryngeal nerve palsy',
      'Sinusitis pathogenesis',
      'Hearing loss types',
    ],
  },
  {
    id:          'ophthalmology',
    label:       'Ophthalmology',
    icon:        '👁',
    color:       'physio',
    accent:      '#ffd60a',
    description: 'Eye diseases & vision',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Glaucoma types',
      'Cataract pathogenesis',
      'Retinal detachment',
      'Diabetic retinopathy',
      'Cranial nerve eye palsies',
    ],
  },
  {
    id:          'radiology',
    label:       'Radiology',
    icon:        '📡',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Imaging & interpretation',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'Chest X-ray reading',
      'CT vs MRI indications',
      'Contrast media reactions',
      'Radiation protection',
      'Common radiological signs',
    ],
  },
  {
    id:          'anesthesia',
    label:       'Anesthesia',
    icon:        '💉',
    color:       'pharma',
    accent:      '#4df7c8',
    description: 'Anesthetic pharmacology & practice',
    year:        3,
    discipline:  'mbbs',
    topics: [
      'General anaesthesia stages',
      'Local anaesthetic types',
      'Neuromuscular blockers',
      'Airway management',
      'Malignant hyperthermia',
    ],
  },
  {
    id:          'forensic',
    label:       'Forensic Medicine',
    icon:        '🔎',
    color:       'patho',
    accent:      '#fb923c',
    description: 'Medical jurisprudence & toxicology',
    year:        2,
    discipline:  'mbbs',
    topics: [
      'Post-mortem changes',
      'Types of asphyxia',
      'Poisoning classification',
      'Wound types & age estimation',
      'Medical negligence',
    ],
  },
  {
    id:          'community-medicine',
    label:       'Community Medicine',
    icon:        '🌍',
    color:       'green',
    accent:      '#0df27d',
    description: 'Public health & epidemiology',
    year:        2,
    discipline:  'mbbs',
    topics: [
      'Epidemiological study types',
      'Vaccination schedules',
      'Biostatistics basics',
      'National health programmes',
      'Levels of prevention',
    ],
  },
  {
    id:          'immunology',
    label:       'Immunology',
    icon:        '🛡',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Immune system, hypersensitivity & immunodeficiency',
    year:        2,
    discipline:  'mbbs',
    topics: [
      'Innate vs adaptive immunity',
      'Hypersensitivity types I-IV',
      'MHC and antigen presentation',
      'Immunodeficiency disorders',
      'Autoimmune diseases',
    ],
  },

  // ──────────────────────────────────────────────────────────────
  // BDS Subjects
  // ──────────────────────────────────────────────────────────────
  {
    id:          'oral-biology',
    label:       'Oral Biology',
    icon:        '🦷',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Structure & function of oral tissues',
    year:        1,
    discipline:  'bds',
    topics: [
      'Tooth development stages',
      'Enamel formation',
      'Dentin structure',
      'Pulp histology',
      'Periodontal ligament',
    ],
  },
  {
    id:          'dental-anatomy',
    label:       'Dental Anatomy',
    icon:        '🦴',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Tooth morphology & occlusion',
    year:        1,
    discipline:  'bds',
    topics: [
      'Tooth surface landmarks',
      'Maxillary molar anatomy',
      'Mandibular premolar anatomy',
      'Dental occlusion types',
      'Root canal morphology',
    ],
  },
  {
    id:          'oral-histology',
    label:       'Oral Histology',
    icon:        '🔬',
    color:       'biochem',
    accent:      '#c77dff',
    description: 'Microscopic structure of oral tissues',
    year:        1,
    discipline:  'bds',
    topics: [
      'Oral mucosa types',
      'Salivary gland histology',
      'Tongue papillae',
      'TMJ histology',
      'Cementum structure',
    ],
  },
  {
    id:          'oral-pathology',
    label:       'Oral Pathology',
    icon:        '🧫',
    color:       'patho',
    accent:      '#fb923c',
    description: 'Diseases of oral cavity & jaws',
    year:        2,
    discipline:  'bds',
    topics: [
      'Oral leukoplakia',
      'Ameloblastoma',
      'Dental caries pathology',
      'Periodontal disease stages',
      'Oral squamous cell carcinoma',
    ],
  },
  {
    id:          'dental-materials',
    label:       'Dental Materials',
    icon:        '⚙️',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Properties & uses of dental materials',
    year:        2,
    discipline:  'bds',
    topics: [
      'Dental amalgam composition',
      'Composite resin types',
      'GIC setting reaction',
      'Impression materials',
      'Dental cement classification',
    ],
  },
  {
    id:          'operative-dentistry',
    label:       'Operative Dentistry',
    icon:        '🪥',
    color:       'green',
    accent:      '#0df27d',
    description: 'Cavity preparation & restoration',
    year:        2,
    discipline:  'bds',
    topics: [
      'Black\'s cavity classification',
      'Cavity preparation principles',
      'Bonding techniques',
      'Isolation methods',
      'Restoration finishing',
    ],
  },
  {
    id:          'endodontics',
    label:       'Endodontics',
    icon:        '📍',
    color:       'patho',
    accent:      '#fb923c',
    description: 'Root canal treatment & pulp therapy',
    year:        3,
    discipline:  'bds',
    topics: [
      'Root canal instrumentation',
      'Irrigation solutions',
      'Obturation techniques',
      'Pulp vitality testing',
      'Endodontic emergencies',
    ],
  },
  {
    id:          'prosthodontics',
    label:       'Prosthodontics',
    icon:        '🦿',
    color:       'pharma',
    accent:      '#4df7c8',
    description: 'Dentures, crowns & implants',
    year:        3,
    discipline:  'bds',
    topics: [
      'Complete denture impressions',
      'Crown preparation principles',
      'Fixed partial denture design',
      'Implant components',
      'Removable partial denture clasps',
    ],
  },
  {
    id:          'periodontology',
    label:       'Periodontology',
    icon:        '🩺',
    color:       'physio',
    accent:      '#ffd60a',
    description: 'Periodontal diseases & treatment',
    year:        3,
    discipline:  'bds',
    topics: [
      'Gingivitis vs periodontitis',
      'Periodontal probing',
      'Scaling and root planing',
      'Periodontal flap surgery',
      'Periodontal risk factors',
    ],
  },
  {
    id:          'orthodontics',
    label:       'Orthodontics',
    icon:        '😁',
    color:       'biochem',
    accent:      '#c77dff',
    description: 'Malocclusion & tooth movement',
    year:        3,
    discipline:  'bds',
    topics: [
      'Angle\'s classification',
      'Cephalometric analysis',
      'Orthodontic force principles',
      'Growth modification',
      'Retainer types',
    ],
  },
  {
    id:          'oral-surgery',
    label:       'Oral & Maxillofacial Surgery',
    icon:        '🔪',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Extractions, trauma & jaw surgery',
    year:        3,
    discipline:  'bds',
    topics: [
      'Tooth extraction technique',
      'Impacted third molar',
      'Maxillofacial trauma',
      'TMJ disorders',
      'Local anaesthesia in dentistry',
    ],
  },
  {
    id:          'community-dentistry',
    label:       'Community Dentistry',
    icon:        '🌍',
    color:       'green',
    accent:      '#0df27d',
    description: 'Public dental health & epidemiology',
    year:        2,
    discipline:  'bds',
    topics: [
      'DMFT index',
      'Fluoride in caries prevention',
      'Dental health surveys',
      'Pit and fissure sealants',
      'School dental health programmes',
    ],
  },
  {
    id:          'pediatric-dentistry',
    label:       'Pediatric Dentistry',
    icon:        '👶',
    color:       'physio',
    accent:      '#ffd60a',
    description: 'Child dental health & behaviour',
    year:        3,
    discipline:  'bds',
    topics: [
      'Primary tooth eruption',
      'Behaviour management',
      'Pulpotomy vs pulpectomy',
      'Space maintainers',
      'Early childhood caries',
    ],
  },
  {
    id:          'oral-medicine',
    label:       'Oral Medicine',
    icon:        '💊',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Oral manifestations of systemic disease',
    year:        3,
    discipline:  'bds',
    topics: [
      'Oral ulceration causes',
      'Salivary gland disorders',
      'Oral manifestations of HIV',
      'Burning mouth syndrome',
      'Facial pain diagnosis',
    ],
  },
  {
    id:          'bds-anatomy',
    label:       'General Anatomy',
    icon:        '🦴',
    color:       'anatomy',
    accent:      '#ff4d6d',
    description: 'Head, neck & oral cavity anatomy',
    year:        1,
    discipline:  'bds',
    topics: [
      'Head & neck regions',
      'Oral cavity structures',
      'Cranial nerves overview',
      'Blood supply of head & neck',
      'Lymphatic drainage of oral cavity',
      'TMJ anatomy & movements',
    ],
  },
  {
    id:          'bds-physiology',
    label:       'Physiology',
    icon:        '⚡',
    color:       'physio',
    accent:      '#ffd60a',
    description: 'General & oral physiology',
    year:        1,
    discipline:  'bds',
    topics: [
      'Salivary secretion physiology',
      'Mastication mechanism',
      'Taste sensation pathway',
      'Calcium & phosphate homeostasis',
      'Tooth eruption physiology',
      'Pain pathways in dentistry',
    ],
  },
  {
    id:          'bds-biochemistry',
    label:       'Biochemistry',
    icon:        '🧬',
    color:       'biochem',
    accent:      '#c77dff',
    description: 'Biochemistry relevant to dentistry',
    year:        1,
    discipline:  'bds',
    topics: [
      'Collagen synthesis & dental tissues',
      'Calcium metabolism',
      'Fluoride biochemistry',
      'Vitamin D metabolism',
      'Enzymes in oral health',
      'Protein-energy malnutrition & oral effects',
    ],
  },
  {
    id:          'bds-pathology',
    label:       'General Pathology',
    icon:        '🔬',
    color:       'patho',
    accent:      '#fb923c',
    description: 'General pathology for dental students',
    year:        2,
    discipline:  'bds',
    topics: [
      'Inflammation types & oral relevance',
      'Neoplasia basics — benign vs malignant',
      'Wound healing & tissue repair',
      'Immune responses in periodontal disease',
      'Granulomatous diseases',
      'Amyloidosis',
    ],
  },
  {
    id:          'bds-pharmacology',
    label:       'Pharmacology',
    icon:        '💊',
    color:       'pharma',
    accent:      '#4df7c8',
    description: 'Drugs used in dental practice',
    year:        2,
    discipline:  'bds',
    topics: [
      'Local anaesthetics — mechanism & toxicity',
      'Antibiotics in dentistry',
      'Analgesics — NSAIDs, paracetamol, opioids',
      'Sedation in dentistry',
      'Anticoagulants & dental procedures',
      'Drug interactions in dental practice',
    ],
  },
  {
    id:          'bds-microbiology',
    label:       'Microbiology',
    icon:        '🦠',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Oral & general microbiology',
    year:        2,
    discipline:  'bds',
    topics: [
      'Oral microbiome & biofilm',
      'Streptococcus mutans & caries',
      'Periodontal pathogens',
      'Hepatitis B & C — dental relevance',
      'HIV oral manifestations',
      'Sterilisation & disinfection',
    ],
  },
  {
    id:          'bds-radiology',
    label:       'Radiology',
    icon:        '📡',
    color:       'micro',
    accent:      '#38bdf8',
    description: 'Dental imaging & interpretation',
    year:        3,
    discipline:  'bds',
    topics: [
      'Periapical & bitewing radiographs',
      'OPG interpretation',
      'CBCT in dentistry',
      'Radiographic anatomy of teeth',
      'Radiation protection principles',
      'Common radiographic errors',
    ],
  },
]

export const SUBJECT_MAP: Record<SubjectId, Subject> = Object.fromEntries(
  SUBJECTS.map(s => [s.id, s])
) as Record<SubjectId, Subject>

export function getSubject(id: SubjectId): Subject {
  return SUBJECT_MAP[id] ?? SUBJECTS[0]
}

export function getSubjectsByDiscipline(discipline: Discipline): Subject[] {
  return SUBJECTS.filter(s => s.discipline === discipline)
}

export function getMbbsSubjects(): Subject[] {
  return getSubjectsByDiscipline('mbbs')
}

export function getBdsSubjects(): Subject[] {
  return getSubjectsByDiscipline('bds')
}