import Link from 'next/link'

export const metadata = { title: 'Terms of Service — MnemonicFlow' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-void text-ink-primary">
      <nav className="px-6 py-4 flex items-center gap-3 max-w-3xl mx-auto">
        <Link href="/login" className="text-xs text-ink-tertiary hover:text-neon-green transition-colors">
          ← Back
        </Link>
      </nav>
      <article className="max-w-3xl mx-auto px-6 pb-16 space-y-8">
        <header className="space-y-2">
          <h1 className="text-2xl font-bold font-display text-ink-primary">Terms of Service</h1>
          <p className="text-xs text-ink-tertiary">Last updated: August 31, 2026</p>
        </header>

        <Section title="1. Acceptance of Terms">
          By creating an account or using MnemonicFlow (&quot;the Service&quot;), you agree to these Terms of Service. If you do not agree, do not use the Service.
        </Section>

        <Section title="2. Description of Service">
          MnemonicFlow is an AI-powered educational platform designed for medical and dental students (MBBS/BDS). The Service generates study mnemonics, flashcards, quizzes, high-yield revision notes, and clinical simulations. The Service is provided &quot;as is&quot; for educational purposes only.
        </Section>

        <Section title="3. Educational Disclaimer">
          <p>MnemonicFlow is a supplementary study aid. It is <strong>not a substitute</strong> for standard medical textbooks, peer-reviewed literature, clinical guidelines, or professional medical training.</p>
          <p className="mt-2">AI-generated content may contain inaccuracies. Always verify critical medical information against recognized standard textbooks and current clinical guidelines before applying it in any clinical or examination context.</p>
          <p className="mt-2">MnemonicFlow does not provide medical advice, diagnosis, or treatment recommendations. Nothing generated by the Service should be construed as clinical guidance.</p>
        </Section>

        <Section title="4. User Accounts">
          <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-sm text-ink-secondary">
            <li>Provide accurate registration information</li>
            <li>Notify us immediately of any unauthorized access to your account</li>
            <li>Accept responsibility for all activity that occurs under your account</li>
          </ul>
          <p className="mt-2">We reserve the right to suspend or terminate accounts that violate these Terms.</p>
        </Section>

        <Section title="5. Acceptable Use">
          You agree not to:
          <ul className="list-disc pl-5 mt-2 space-y-1 text-sm text-ink-secondary">
            <li>Use the Service for any unlawful purpose or in violation of any applicable regulations</li>
            <li>Attempt to gain unauthorized access to other users&apos; accounts or system infrastructure</li>
            <li>Reverse-engineer, scrape, or extract data from the Service beyond your personal educational use</li>
            <li>Share your account credentials with third parties</li>
            <li>Use the Service to generate content for commercial redistribution without explicit permission</li>
          </ul>
        </Section>

        <Section title="6. Intellectual Property">
          The MnemonicFlow platform, its design, branding, and underlying technology are owned by MnemonicFlow. AI-generated study content created through your use of the Service is available for your personal educational use. You retain ownership of any original input you provide.
        </Section>

        <Section title="7. Data and Privacy">
          Your use of the Service is also governed by our <Link href="/privacy" className="text-neon-green hover:underline">Privacy Policy</Link>. We collect and process personal data as described in that policy. By using the Service, you consent to such processing.
        </Section>

        <Section title="8. Limitation of Liability">
          To the maximum extent permitted by law, MnemonicFlow shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, including but not limited to reliance on any information obtained through the Service.
        </Section>

        <Section title="9. Service Availability">
          We strive to maintain continuous availability but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.
        </Section>

        <Section title="10. Changes to Terms">
          We may update these Terms from time to time. Material changes will be communicated through the Service or by email. Continued use of the Service after changes constitutes acceptance of the updated Terms.
        </Section>

        <Section title="11. Contact">
          For questions about these Terms, contact us through the MnemonicFlow platform.
        </Section>
      </article>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-base font-bold font-display text-ink-primary">{title}</h2>
      <div className="text-sm text-ink-secondary leading-relaxed">{children}</div>
    </section>
  )
}
